#!/usr/bin/env bash

# Check for the correct number of arguments
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the arguments to variables
FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer the file
scp -i "${SSH_KEY}" -o StrictHostKeyChecking=no "${FILE}" "${USERNAME}@${IP}:~/"
