#!/usr/bin/env bash
# Configurer une redirection 301 sur Nginx

# Mettre à jour les packages et installer Nginx
apt-get update
apt-get install -y nginx

# Configurer Nginx pour ajouter une redirection 301
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Redémarrer Nginx pour appliquer les changements
service nginx restart
