#!/usr/bin/env bash
# Configurer une page 404 personnalisée sur Nginx

# Mettre à jour les packages et installer Nginx
apt-get update
apt-get install -y nginx

# Créer une page HTML personnalisée pour les erreurs 404
cat <<EOF > /var/www/html/404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>
EOF

# Configurer Nginx pour utiliser la page 404 personnalisée
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Redémarrer Nginx pour appliquer les changements
service nginx restart
