#!/usr/bin/env bash
# Configurer un nouveau serveur Ubuntu pour qu'il soit identique à web-01 et ajouter un en-tête HTTP personnalisé

# Mettre à jour les packages et installer Nginx
apt-get update
apt-get install -y nginx

# Configurer Nginx pour ajouter un en-tête HTTP personnalisé
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
    }
}
EOF

# Redémarrer Nginx pour appliquer les changements
service nginx restart
