#!/usr/bin/env bash
# 101-manage_my_process script

PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="./manage_my_process"

start() {
    $PROCESS_SCRIPT &
    echo $! > $PID_FILE
    echo "manage_my_process started"
}

stop() {
    if [ -f $PID_FILE ]; then
        PID=$(cat $PID_FILE)
        kill $PID
        rm -f $PID_FILE
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
