#!/usr/bin/env bash
# Afficher 10 fois "Best School" en  while loop, et dire "Hi" a 9

count=1

while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 4 ]
    then
        echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    fi
    ((count++))
done